name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload and run script on EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: 184.73.139.147

        run: |
          USER_NAME="ubuntu"
          
          echo "Debugging Environment Variables"
          echo "Hostname: ${HOSTNAME}"
          echo "Username: ${USER_NAME}"
          
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          # Copy the script to the EC2 instance
          echo "Copying script to EC2 instance..."
          scp -o StrictHostKeyChecking=no -i private_key ./00_ec2/ec2_user_data.sh ubuntu@${HOSTNAME}:/home/ubuntu/ec2_user_data.sh
          
          # Verify the file was copied correctly
          echo "Verifying script on EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${HOSTNAME} 'ls -l /home/ubuntu/ec2_user_data.sh'
          
          # SSH into the EC2 instance and run the script
          echo "Running script on EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${HOSTNAME} '
            chmod +x /home/ubuntu/ec2_user_data.sh &&
            /home/ubuntu/ec2_user_data.sh
          '
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

